### ISSUE TITLE
Not possible on iOS right ? 

### ISSUE THREAD

**Issue by avichou** [stravo1/obsidian-gdrive-sync#12]
Not sure I can ask this here but I imagine it's completely incompatible with iOS isn't it

**Comment by mayorbest23** [comment]
I apologise for re-awakening this thread! I am grateful for this free sync :) I am a total novice and have finished the desktop steps but cannot seem to figure out how to copy the files over to my iPhone. Here's what I have done to try and remedy this: 
- Copy and paste entire folder from Mac to iPhone's files; opens in Obsidian only after I have created a dummy vault, but files do not open or sync
- Copy and paste only .obsidian file from Mac to iPhone in Obsidian Files. Did not result in anything.

I have tried googling how to copy an Obsidian file to my iPhone but I have come up unsuccessful. Any suggestions much appreciated. Regardless, stravo1's program has significantly helped me with my transition from Notion to Obsidian -- thank you!!

**Comment by stravo1** [comment]
hello @mayorbest23 !

i will try and get the exact procedure, but until then you can join the discord server https://discord.com/invite/dPasX4Ac2P
there are a few iOS users here :)

**Comment by poopsicles** [comment]
- First, with your Obsidian vault set up on your desktop, navigate to its parent folder in your file explorer (Finder if on Mac, File Explorer for Windows).
- Compress the entire vault folder (containing the `.obsidian` folder and all the `.md` files) in the explorer by right-clicking the folder and choosing the appropriate option.
- On your iOS device, create a vault with the same name (if your vault is called "vaulty", compressing it should make a "vaulty.zip", so make a vault called "vaulty" on your iOS device). Make sure to uncheck the "Store in iCloud" option. 
- To confirm it's all good so far, check the Obsidian folder in the "On your iPad/iPhone" folder in Files. It should pretty much be empty except for the vault we just made.
- Get the compressed file from your desktop to mobile however you might like (personally I use Telegram to send a message to myself, but since it's a .zip it shouldn't matter how you do it)
- Move the .zip to this Obsidian data folder, beside the empty vault we just made.
- Delete the (empty) vault folder, and unzip the zip we have by tapping and holding on it and selecting "Extract".
- Now we should have effectively the "same" vault as before, except now it's populated with files.
- Close Obsidian from the app switcher and reopen it.
- Hopefully your files should sync after a bit once the extension loads.

**Comment by Eizenhorn** [comment]
> * First, with your Obsidian vault set up on your desktop, navigate to its parent folder in your file explorer (Finder if on Mac, File Explorer for Windows).
> * Compress the entire vault folder (containing the `.obsidian` folder and all the `.md` files) in the explorer by right-clicking the folder and choosing the appropriate option.
> * On your iOS device, create a vault with the same name (if your vault is called "vaulty", compressing it should make a "vaulty.zip", so make a vault called "vaulty" on your iOS device). Make sure to uncheck the "Store in iCloud" option.
> * To confirm it's all good so far, check the Obsidian folder in the "On your iPad/iPhone" folder in Files. It should pretty much be empty except for the vault we just made.
> * Get the compressed file from your desktop to mobile however you might like (personally I use Telegram to send a message to myself, but since it's a .zip it shouldn't matter how you do it)
> * Move the .zip to this Obsidian data folder, beside the empty vault we just made.
> * Delete the (empty) vault folder, and unzip the zip we have by tapping and holding on it and selecting "Extract".
> * Now we should have effectively the "same" vault as before, except now it's populated with files.
> * Close Obsidian from the app switcher and reopen it.
> * Hopefully your files should sync after a bit once the extension loads.

Thanks a lot working fine on Iphone
