### ISSUE TITLE
Initial upload: no folder creaded

### ISSUE THREAD

**Issue by kkaal** [stravo1/obsidian-gdrive-sync#13]
Hi,

the login process was smooth, but I found 2 problems:

1. I have my vault in a subfolder in Drive. For any reason, I could not install it that it would use my vault in the subfolder. 
2. When I let him use whatever folder, it created /obsidian/myVault. Fine, but when it initially uploaded, it created files with the path in the filename, joined with the slash: "MyVaoult/directory1/subdirectory1/filename1"

Thus, I am sorry, it is not usable for me.

**Comment by stravo1** [comment]
hello!
thanks for trying out the plug-in!

why the plugin doesn't maintain the folder structure in drive?
the plug-in has its own method of uploading and syncing files between the vault and Drive, it doesn't try to imitate the folder structure, instead it uploads and syncs all the files based on their "relative paths", so that behaviour is expected. https://github.com/stravo1/obsidian-gdrive-sync/issues/10#issuecomment-2028542710

why does the plug-in create a separate folder named "obsidian" within your Drive and store all necessary files under subfolders (which are named after your vault)?
this is because the plug-in only has access to the files and folders it creates itself, NOT the entire Drive (for obvious security reasons). so it creates a folder "obsidian" which ensures that the plug-in has access to the files and folders under that "obsidian" folder and it doesn't touch anything else.

![Screenshot_20240404-004631.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/76593476/fe41a5ca-4804-4894-910a-d89c7907336d)

thus all the issues you faced are expected and they're not bugs unfortunately, that's how the plug-in works.
