### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by Zik42** [stravo1/obsidian-gdrive-sync#24]
Hi, I am very interested in your project. That is what I was looking for. I have a question about security? Isn't it vulnerability to use someones url for authorising app, I see it goes to the red-formula-303406.ue.r.appspot.com. Any plans to give user decide what app to use for auth?

**Comment by stravo1** [comment]
tldr: the plug-in just requires the refresh token, how you retrieve the token is none of it's concern, you can entirely bypass the URL if you can get the refresh token by your own means.

hello!

that URL is for a GCP App Engine which handles the refresh token exchange, it doesn't store the refresh token but simply sends it back. (Google [no more supports](https://developers.google.com/identity/sign-in/web/deprecation-and-sunset) authentication directly via their JavaScript library, it needs to be done via a server).

here's the repo which has the code that runs on the GCP App Engine:
https://github.com/stravo1/gis-app-engine

but of course users have no way of verifying what code is running on the GCP App Engine, so the concern is justified.

however the other alternative is that users have to set-up their own server that does that exchange for them, which is not something that everyone is willing to go through.

the plug-in just requires the refresh token to work, how the user retrieves it is up to the user. the login URL is just to help them get the token. users who are willing to set-up their own server or their own process of retrieving the refresh token are very much encouraged to do so.

**Comment by Zik42** [comment]
I will try do it, thank you for great response. Waiting for release 💪

**Comment by beliaev-maksim** [comment]
hosting your own server will not be enough, user will need to specify their own URL, which is currently hardcoded: 
https://github.com/stravo1/obsidian-gdrive-sync/blame/3f8f7ba7564fa04c1c5a44b8d61f1406dce4957d/main.ts#L87

The problem isn't just what the app does or whether it stores data. If the service is hijacked, all refresh tokens will be sent to one location, exposing all Obsidian notes from all users to the attacker.

**Comment by stravo1** [comment]
correct, thank you for specifying it here, that's a detail that i missed in my earlier comment. only obtaining the refresh token by yourself won't entirely solve the issue. the url endpoint also exchanges the refresh token for an access token, so the url too needs to be changed. and yes, the code, as you have pointed out, is currently hard-coded with the URL, and someone who can figure out their own implementation of the GIS server and host it, can of course change the URL and rebuild the plug-in. I have made my server code open as well.

the fact remains that involving a server which is out of the user's control is a serious security risk, how it's compromised or how it's misused by the server owner without even any third-party compromising it, is out of the control of the user.

i can ofcourse add an input text box which if filled will use the value put there as the url endpoint instead of the one hard-coded but i believe currently the users who would go to the length of doing that can also rebuild the plug-in with their own url. if the need arises/many users demand that they would like to host their own backend i would add the input box (of course i would love that, that would mean I won't need to pay GCP if a lot of users use this plug-in) but currently with the small number of users i can afford to keep the backend hosted for people who would like to not go through the process of getting their own server and rebuilding the plug-in :)

**Comment by KorigamiK** [comment]
You could, instead of hosting the backend yourself, create a CI/CD pipeline which will deploy to the endpoint that others can verify

**Comment by stravo1** [comment]
> You could, instead of hosting the backend yourself, create a CI/CD pipeline which will deploy to the endpoint that others can verify

I would love to make sure that others can trust the backend.

But my question would be that even if a pipeline creates the endpoint, we are still involving a server, a server which only I have access to. I can change the code after the automated deployment is complete. Am I missing something?

Also the backend code did not change since day one, so re-deploying the backend via a pipeline (say on every release) is unnecessary.

**Comment by KorigamiK** [comment]
> > You could, instead of hosting the backend yourself, create a CI/CD pipeline which will deploy to the endpoint that others can verify
> 
> I would love to make sure that others can trust the backend.
> 
> But my question would be that even if a pipeline creates the endpoint, we are still involving a server, a server which only I have access to. I can change the code after the automated deployment is complete. Am I missing something?
> 
> Also the backend code did not change since day one, so re-deploying the backend via a pipeline (say on every release) is unnecessary.

I only mention ci because it's easy to create a image and upload to something like GitHub Container Registry (ghcr.io) which is free as well. would make the backend a little more transparent atleast

**Comment by stravo1** [comment]
i am not too much familiar with docker and containers so pardon if i don't understand something. 

the backend code is already open source, you can find the link to the repo in the first comment i made under this issue. does creating a container image of the app make it anymore transparent than it already is?
