### ISSUE TITLE
Filenames with "/" issue

### ISSUE THREAD

**Issue by jackcreator** [stravo1/obsidian-gdrive-sync#34]
Filenames after upload are folder_name + "/" + note_name.md
I can't sync it with Android because of "/" in the filenames
Is there any way to create a structure with files inside folders?

**Comment by stravo1** [comment]
hello!

can you explain what you mean by "can't sync with Android"?
sync works well with Android as far as i know, because i myself use an Android phone 😅

Obsidian doesn't allow you to add "/" in the filename because that's probably reserved for tracking the path, so i didn't understand what was the issue with the name format?

:)

**Comment by jackcreator** [comment]
![Screenshot_20240706-104507.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/47914583/3b93212d-7066-4f1b-ae01-abd354167106)

After uploading the vault to the Google drive I get this, with / inside filename.

**Comment by stravo1** [comment]
that is how the plug-in works, it tracks the folder structure with the file name, it doesn't try to replicate the folder structure on Drive.

**Comment by stravo1** [comment]
what is the issue you're facing? this is expected behaviour, shouldn't be an issue in syncing

**Comment by jackcreator** [comment]
> what is the issue you're facing? this is expected behaviour, shouldn't be an issue in syncing 
> 
> https://github.com/stravo1/obsidian-gdrive-sync/issues/10#issuecomment-2028542710

Ok, got it
