### ISSUE TITLE
COMMUNITY PLUGINS SYNC ISSUE ACROSS DEVICES

### ISSUE THREAD

**Issue by vinay24794** [stravo1/obsidian-gdrive-sync#43]
I have couple of plugins on my PC vault. Rest is all synced onto my phone except community plugins. Is there any fix or settings like these are device independent ??

**Comment by stravo1** [comment]
unfortunately currently only notes and attachments are supported, i am researching whether i can extend it to the entire vault, i.e., with all plug-ins and their settings

**Comment by vinay24794** [comment]
Thanks for the reply @stravo1!

One more observation: For all newly created files, sync works perfectly across devices with no downtime. However, when editing an existing file, synchronization of changes is inconsistent—it's either a hit or a miss.

After trying both methods, i.e., your method vs. the third-party Autodrive method, I can confidently say your method is absolutely brilliant in terms of sync times. I really appreciate the ability to achieve synchronization without needing a third-party app. Great job, brother! Keep it up!

**Comment by stravo1** [comment]
there's an indicator at the bottom (only for desktop app though) which shows when the sync is in process, when there's a check mark that means all changes have been synced... unfortunately for mobile there's no such status bar at the bottom so no way of indicating whether the sync is complete or not. Working on an experimental feature which tells the status of sync via the color of the cursor on mobile.


for now it's advisable that with good internet connection and moderate file size sync should take around 4 5 secs, at max 10secs... so after all changes are made please do wait 10secs before closing the app or file... also it is advisable (although it _should_ work just fine) to not open the same file on more than one device at a time because it might to lead to race conditions

**Comment by vinay24794** [comment]
Today, I encountered a sync issue, so I had to reopen the issue, Please don't mind.

I merged a file with another on my PC, There was no race condition, as the Obsidian app on my phone was closed. However, when I checked after about an hour, the files hadn't merged on my phone.

How to deal with this sync issue of 'Merging files' ??

**Comment by stravo1** [comment]
i didn't get the problem, if it's you don't mind you can join the discord server to send screenshots and help me further understand the issue and debug it

thanks :)
