### ISSUE TITLE
obsidian-gdrive-sync breaks up properties from other plugins after adding lastSync.

### ISSUE THREAD

**Issue by mrsousa** [stravo1/obsidian-gdrive-sync#56]
Hi Sayantan,

First of all, thank you for the plugin.

I'm using both [obsidian-gdrive-sync]() and [voicenotes-sync](https://github.com/mysticcoders/voicenotes-sync).

When a new note from voicenotes-sync is synced, it comes with some properties, as shown in the image below:

![image](https://github.com/user-attachments/assets/0a940d16-23db-451d-bddb-4bb497280df8)

However, after a few seconds, gdrive-sync triggers and adds the lastSync property, which leads to the following issue:

![image](https://github.com/user-attachments/assets/116e86b9-edc7-42f1-b246-b1c983b5ca1e)

If I remove the spaces in front of the voicenotes-sync properties:

![image](https://github.com/user-attachments/assets/2cd32472-6760-450d-b2ea-187c7bc066bc)

The properties reappear correctly:

![image](https://github.com/user-attachments/assets/824e7cdf-2f3b-4544-96da-19054041d673)

Is there a way to prevent this conflict?

Best Regards,
David

**Comment by mrsousa** [comment]
Hi there.

I have sent you 3 files; before sync, synced, and fixed.

[note_before.md](https://github.com/user-attachments/files/17476217/note_before.md)
[note_fixed.md](https://github.com/user-attachments/files/17476218/note_fixed.md)
[note_sync.md](https://github.com/user-attachments/files/17476219/note_sync.md)

David

**Comment by stravo1** [comment]
https://github.com/user-attachments/assets/cde9e5e9-e722-47c3-9f39-f3af4500a5f1
<img width="1440" alt="Screenshot 2024-10-28 at 12 08 47 PM" src="https://github.com/user-attachments/assets/355292ac-0152-40f1-a1dc-1c92230f1ffc">

seems like the error occurs because the other plugin adds whitespace before the properties, which if they exist separately then is not illegal but when mixed with properties with no whitespaces they cause issues. as you can see default behaviour is to NOT add whitespaces in front of properties. so there is nothing i can do here, its the other plugin causing this issue.

**Comment by mrsousa** [comment]
Sayantan,

thanks for the replay.

Have a nice week.

David

**Comment by stravo1** [comment]
thanks for being one of the sweetest people to submit an issue of this repo :) 

have a great week
