### ISSUE TITLE
Desktop and Mobile: same folder on GDrive

### ISSUE THREAD

**Issue by daveshortpants** [stravo1/obsidian-gdrive-sync#6]
Hi Stravos, 

I'm brand new to Obsidian.  I installed the plugin on my desktop first but would like to write/edit as I go. 

Do I have to install the plug-in on the mobile version of Obsidian? (I'm thinking, yes.)

How do I point the mobile plugin to the same folder I'm using for my desktop?

Thank you for any input!

**Comment by stravo1** [comment]
If you have completed setting up the plug-in on your desktop vault then you need to create a vault with the **same name** in your mobile and copy the `obsidian-gdrive-sync` folder to the vault's location (under `.obsidian/plugins`). Then you need to simply login using the refresh token, the plug-in will **automatically detect** whether you have a backed up vault with the same name as in your Google Drive as the one the plug-in has been installed.

Assuming you have an Android device, you just need to copy paste the `obsidian-gdrive-sync` folder using a file explorer.

[Link to a video walkthrough](https://github.com/stravo1/obsidian-gdrive-sync/issues/4#issuecomment-2022138355)

However if you're using an iPhone, the easiest option is to copy the entire vault from your desktop to your phone.

**Comment by daveshortpants** [comment]
Thank you, Stravos! 

I am using a Pixel 6 Pro. 
I'll let you know if it worked for me or not. 

and thanks for the vid walkthrough!

**Comment by daveshortpants** [comment]
Hi Stravos, 

Problem 1: I tried to get cute and organize my vault in my google drive. Fixed it with just letting Obsidian make my folder. 

Problem 2: my vaults on my phone and laptop don't seem to be saving anything to google drive. Even with a new note.
Exhibit A:
![Screenshot 2024-03-27 1 50 06 PM](https://github.com/stravo1/obsidian-gdrive-sync/assets/165199023/dbbac813-5e44-4571-bd7b-157a5e80a9d4)

Problem 3: The notes I create, don't really go into the folders that I want them to in obsidian making 2 files that aren't carbon copies. 
Exhibit B &C: 
![Screenshot_20240327-134146](https://github.com/stravo1/obsidian-gdrive-sync/assets/165199023/1d7ee75e-932d-4875-b294-05021021b900)
![Screenshot 2024-03-27 1 42 11 PM](https://github.com/stravo1/obsidian-gdrive-sync/assets/165199023/0e357d73-77f0-401e-ae37-634fe3e78691)

Problem 4: Also the upload and download functions don't seem to work for me.

Any thoughts? 

Thank you!

**Comment by stravo1** [comment]
can you show me the plug-in settings once?

**Comment by daveshortpants** [comment]
![image](https://github.com/stravo1/obsidian-gdrive-sync/assets/165199023/6463b581-d3c1-4688-958a-f7ff6e58a33b)
this is the desktop setup

**Comment by daveshortpants** [comment]
![Screenshot_20240327-142051.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/165199023/a27416e8-6dd6-4d65-91c9-17f798666293)

![Screenshot_20240327-142100.png](https://github.com/stravo1/obsidian-gdrive-sync/assets/165199023/b5feff73-af49-4539-be88-b02a89e699c9)

This is the phone setup

**Comment by stravo1** [comment]
Did you "intialize" the vault after you logged in? If so then the plug-in should create a folder named "obsidian" in your drive under which it will create a folder named after your vault and in that folder it will store all the files.

<img width="1440" alt="Screenshot 2024-03-28 at 2 47 03 AM" src="https://github.com/stravo1/obsidian-gdrive-sync/assets/76593476/7d523949-55df-4d1b-867d-bea7c1f8f9a5">

and as you can see, instead of creating folders it stores the notes with their absolute path with respect to the vault

**Comment by daveshortpants** [comment]
oh man, i just found that folder... in the trash 🤦‍♂️ *cringe*

I restored it, but the extra files didn't go away, but I'm going to delete and try it out again.

**Comment by daveshortpants** [comment]
It works! 

Problems 1-3 are fixed.

I'm not sure what to do with 4. 

thank you, thank you! 

I can even have both platforms open at the same time.

**Comment by stravo1** [comment]
when you click the upload button does it not show

"Uploading the current file to Google Drive!"
and then
"Uploaded!"

if not then there might be an issue

please note that the upload and download buttons are for manual syncing, for a file which has already been synced automatically, both the buttons would seem to do nothing as the syncing has already been done.

and yes, although you can open the vault on more than one device at the same time and edit a note and see the changes on the other devices, i would not recommend doing that because it will introduce race conditions which might lead to some data loss as the outdated file on a device may try and override the same file being currently being edited on another device.

**Comment by daveshortpants** [comment]
I understand the 4th problem. thank you for explaining that to me. 

yeah, I wouldn't recommend having both instances open either. it was a test to see if I could. 

this is great! and thank you for being so patient!

**Comment by stravo1** [comment]
you're welcome :)

**Comment by yanickrochon** [comment]
I don't know if what I have is the same problem, but I can't have my PC and phone to sync to the same GDrive folder. The PC will sync the vault at the root of my Google Drive (ex: `/test-vault`), but my phone will have the vault under the `obsidian` folder (ex: `/obsidian/test-vault`).

Would be nice to specify the actual folder location on Google Drive instead of having "Init" button.

**Comment by stravo1** [comment]
this is a non repeatable issue which means it happens for some and doesn't for other users, you can delete the folder (even from Bin) in your Drive root, ie, the folder that your PC tries to sync to. then just reopen the obsidian on PC. it should sync automatically to the phone's folder in Drive (that is the correct location).

**Comment by yanickrochon** [comment]
@stravo1 yes, this is what I tried to to, but all I get is the `Init` button in the newly created vault, and pressing that button recreate a new folder in the root folder my my GDrive. In fact, deleting the local vault and recreating it without deleting the GDrive folder (either at the root at inside the `obsidian` folder) creates a duplicate folder at the root.

Not having control as to where the vault is remotely saved is annoying.

**Comment by stravo1** [comment]
you can join the discord so that i can help you troubleshoot the issue. and by design the user doesn't have any choice about the location where the vaults are stored in Drive. the location is obsidian/vault-name.
